/*
 *	NMH's Simple C Compiler, 2011,2012,2022
 *	Error handling
 */

#include "defs.h"
#include "data.h"
#include "decl.h"

// Remove assembly and object code generated by the compiler and assembler so far
static void cleanup(void) {
	if (!O_testonly && NULL != Basefile) {
		remove(newfilename(Basefile, 's'));
		remove(newfilename(Basefile, 'o'));
	}
}

// Principal error reporting function
// Prints error as form: Error: File: Line: Message
// Fatal error emitted when too many errors
void error(char *s, char *a) {
	if (Syntoken) return;
	if (!Errors) cleanup();
	fprintf(stderr, "error: %s: %d: ", File, Line);
	fprintf(stderr, s, a);
	fprintf(stderr, "\n");
	if (++Errors > 10) {
		Errors = 0;
		fatal("too many errors");
	}
}

// Reports fatal error and aborts compilation immediatly
void fatal(char *s) {
	error(s, NULL);
	error("fatal error, stop", NULL);
	exit(EXIT_FAILURE);
}

// Retport invalid input charateristics that are not printable characters
void cerror(char *s, int c) {
	char buf[32];

	if (isprint(c))
		sprintf(buf, "'%c' (\\x%x)", c, c);
	else
		sprintf(buf, "\\x%x", c);
	error(s, buf);
}

// Skips input tokens until it finds one that matches syn parameter
int synch(int syn) {
	int	t;

	t = scan();
	while (t != syn) {
		if (XEOF == t)
			fatal("found EOF in error recovery");
		t = scan();
	}
	Syntoken = syn;
	return t;
}
